# Generated by Django 3.2.13 on 2022-06-14 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Territories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('FRCANT', 'FRCANT'), ('FRCOMM', 'FRCOMM'), ('FREPCI', 'FREPCI'), ('FRDEPA', 'FRDEPA'), ('FRPAYS', 'FRPAYS'), ('FRREGI', 'FRREGI')], max_length=15)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_current', models.BooleanField()),
                ('population', models.BigIntegerField(blank=None)),
                ('official_website_url', models.URLField(blank=True)),
                ('articles_count', models.BigIntegerField(default=0)),
                ('admin_docs_count', models.BigIntegerField(default=0)),
                ('impacters_count', models.BigIntegerField(default=0)),
                ('websites_count', models.BigIntegerField(default=0)),
                ('sources_count', models.BigIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.territories', verbose_name='parent')),
            ],
        ),
    ]
