# Generated by Django 3.2.13 on 2022-06-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_territories_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territories',
            name='official_website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
