# Generated by Django 3.2.13 on 2022-06-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_territories_official_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territories',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
