# Generated by Django 3.2.13 on 2022-06-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_territories_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territories',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
