# Generated by Django 3.2.13 on 2022-06-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_territories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territories',
            name='kind',
            field=models.CharField(choices=[('FRCANT', 'FRCANT'), ('FRCOMM', 'FRCOMM'), ('FREPCI', 'FREPCI'), ('FRDEPA', 'FRDEPA'), ('FRPAYS', 'FRPAYS'), ('FRREGI', 'FRREGI')], db_index=True, max_length=15),
        ),
    ]
